/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tryLogin;

/**
 *
 * @author Im a bug
 */
public class bankTransaction extends javax.swing.JFrame {

    /**
     * Creates new form bankTransaction
     */
    public bankTransaction() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transact = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        balanceInquiry = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pinChange = new javax.swing.JButton();
        fundsTransfer = new javax.swing.JButton();
        deposit = new javax.swing.JButton();
        welcome = new javax.swing.JLabel();
        cashWithdrawal = new javax.swing.JButton();
        pass1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        transact.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        transact.setText("Please select your transaction");
        getContentPane().add(transact, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 200, -1));
        transact.getAccessibleContext().setAccessibleName("Welcome Client!");

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel1.setText("UNIVERSAL BANK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, 20));

        balanceInquiry.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        balanceInquiry.setText("BALANCE INQUIRY");
        balanceInquiry.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        getContentPane().add(balanceInquiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 210, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton2.setText("Exit");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 60, -1));

        pinChange.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        pinChange.setText("PIN CHANGE");
        pinChange.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        pinChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinChangeActionPerformed(evt);
            }
        });
        getContentPane().add(pinChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 210, -1));

        fundsTransfer.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        fundsTransfer.setText("FUNDS TRANSFER");
        fundsTransfer.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        getContentPane().add(fundsTransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 210, -1));

        deposit.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        deposit.setText("DEPOSIT");
        deposit.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        getContentPane().add(deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 210, -1));

        welcome.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        welcome.setForeground(new java.awt.Color(51, 0, 51));
        welcome.setText("Welcome Client!");
        getContentPane().add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        cashWithdrawal.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        cashWithdrawal.setText("CASH WITHDRAWAL");
        cashWithdrawal.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        cashWithdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashWithdrawalActionPerformed(evt);
            }
        });
        getContentPane().add(cashWithdrawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 210, -1));

        pass1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rjpas\\Pictures\\bank.jpg")); // NOI18N
        getContentPane().add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cashWithdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashWithdrawalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashWithdrawalActionPerformed

    private void pinChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinChangeActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        pinChange run = new pinChange();
        run.setVisible(true);
         pinChange pin = new pinChange();
                    pin.juname.setText(this.transact.getText());
                    pin.jpass.setText(this.pass1.getText());
    }//GEN-LAST:event_pinChangeActionPerformed
   
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bankTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bankTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bankTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bankTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bankTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balanceInquiry;
    private javax.swing.JButton cashWithdrawal;
    private javax.swing.JButton deposit;
    private javax.swing.JButton fundsTransfer;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel pass1;
    private javax.swing.JButton pinChange;
    public javax.swing.JLabel transact;
    public javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
